### Importing all the neccessary libraries

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

### Data Loading and observing

In [21]:
# Data Loading and observing:
dataset = pd.read_csv('life_expectancy.csv')
dataset.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [22]:
# checking the columns:
dataset.columns

Index(['Country', 'Year', 'Status', 'Adult Mortality', 'infant deaths',
       'Alcohol', 'percentage expenditure', 'Hepatitis B', 'Measles ', ' BMI ',
       'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ',
       ' HIV/AIDS', 'GDP', 'Population', ' thinness  1-19 years',
       ' thinness 5-9 years', 'Income composition of resources', 'Schooling',
       'Life expectancy'],
      dtype='object')

In [23]:
dataset.describe()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

In [24]:
# Dropping the country column:
dataset = dataset.drop(['Country'], axis = 1)

In [25]:
# Splitting the dataset into labels and features:
labels = dataset.iloc[:, -1]
features = dataset.iloc[:, 0:-1]

### Data preprocessing

In [26]:
# Changing all categorical columns into numerical:
features = pd.get_dummies(features)

# Splitting your data into training set and test sets:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.20, random_state = 23)

# standardizing the numerical columns:
numerical_features = features.select_dtypes(include=['float64', 'int64'])
numerical_columns = numerical_features.columns
 
ct = ColumnTransformer([("only numeric", StandardScaler(), numerical_columns)], remainder='passthrough')

features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.transform(features_test)

### Building the Model

In [27]:
my_model = Sequential()

# Creating an input Layer:
input = InputLayer(input_shape = (features.shape[1], ))

# Adding the input layer to the model:
my_model.add(input)

# Adding a hidden layer to the model:
my_model.add(Dense(64, activation = 'relu'))

# Adding an output layer to the model:
my_model.add(Dense(1))

In [28]:
# Printing the summary of the model:
my_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 64)                1408
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65
=================================================================
Total params: 1,473
Trainable params: 1,473
Non-trainable params: 0
_________________________________________________________________

### Initializing the optimizer and compiling the model:

In [32]:
opt = Adam(learning_rate = 0.01)

my_model.compile(loss = 'mse', metrics = ['mae'], optimizer = opt)

### Fit and evaluate the model

In [33]:
my_model.fit(features_train_scaled, labels_train, epochs = 50, batch_size = 1, verbose = 1)

Epoch 1/50
2350/2350 [==============================] - 4s 2ms/step - loss: 145.6836 - mae: 6.5982
Epoch 2/50
2350/2350 [==============================] - 4s 2ms/step - loss: 24.9043 - mae: 3.7515
Epoch 3/50
2350/2350 [==============================] - 4s 2ms/step - loss: 27.6239 - mae: 3.7101
Epoch 4/50
2350/2350 [==============================] - 3s 1ms/step - loss: 23.6621 - mae: 3.5358
Epoch 5/50
2350/2350 [==============================] - 3s 1ms/step - loss: 19.6403 - mae: 3.2138
Epoch 6/50
2350/2350 [==============================] - 4s 2ms/step - loss: 17.4218 - mae: 3.0744
Epoch 7/50
2350/2350 [==============================] - 4s 2ms/step - loss: 17.2685 - mae: 3.0210
Epoch 8/50
2350/2350 [==============================] - 3s 1ms/step - loss: 16.9244 - mae: 2.9183
Epoch 9/50
2350/2350 [==============================] - 4s 1ms/step - loss: 18.7786 - mae: 3.0144
Epoch 10/50
2350/2350 [==============================] - 3s 1ms/step - loss: 15.0156 - mae: 2.8063
Epoch 11/50
2350/2350 [==============================] - 3s 1ms/step - loss: 14.2092 - mae: 2.7264
Epoch 12/50
2350/2350 [==============================] - 4s 2ms/step - loss: 13.2606 - mae: 2.6423
Epoch 13/50
2350/2350 [==============================] - 3s 1ms/step - loss: 15.1341 - mae: 2.7076
Epoch 14/50
2350/2350 [==============================] - 3s 1ms/step - loss: 11.1329 - mae: 2.4421
Epoch 15/50
2350/2350 [==============================] - 4s 2ms/step - loss: 12.0968 - mae: 2.5509
Epoch 16/50
2350/2350 [==============================] - 3s 1ms/step - loss: 11.4824 - mae: 2.4917
Epoch 17/50
2350/2350 [==============================] - 3s 1ms/step - loss: 11.4545 - mae: 2.4726
Epoch 18/50
2350/2350 [==============================] - 4s 2ms/step - loss: 9.8031 - mae: 2.3500
Epoch 19/50
2350/2350 [==============================] - 4s 1ms/step - loss: 12.1085 - mae: 2.4869
Epoch 20/50
2350/2350 [==============================] - 4s 2ms/step - loss: 9.9971 - mae: 2.3828
Epoch 21/50
2350/2350 [==============================] - 4s 2ms/step - loss: 12.0666 - mae: 2.5086
Epoch 22/50
2350/2350 [==============================] - 4s 2ms/step - loss: 10.4656 - mae: 2.3443
Epoch 23/50
2350/2350 [==============================] - 4s 2ms/step - loss: 9.2305 - mae: 2.2877
Epoch 24/50
2350/2350 [==============================] - 3s 1ms/step - loss: 10.3948 - mae: 2.3416
Epoch 25/50
2350/2350 [==============================] - 4s 2ms/step - loss: 9.9945 - mae: 2.2573
Epoch 26/50
2350/2350 [==============================] - 4s 1ms/step - loss: 9.5800 - mae: 2.2439
Epoch 27/50
2350/2350 [==============================] - 3s 1ms/step - loss: 10.4026 - mae: 2.2183
Epoch 28/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.7019 - mae: 2.1893
Epoch 29/50
2350/2350 [==============================] - 3s 1ms/step - loss: 8.5982 - mae: 2.1726
Epoch 30/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.7771 - mae: 2.1762
Epoch 31/50
2350/2350 [==============================] - 4s 1ms/step - loss: 8.5128 - mae: 2.1693
Epoch 32/50
2350/2350 [==============================] - 4s 2ms/step - loss: 9.4799 - mae: 2.2454
Epoch 33/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.4359 - mae: 2.1419
Epoch 34/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.6607 - mae: 2.1795
Epoch 35/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.9567 - mae: 2.2183
Epoch 36/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.9900 - mae: 2.1701
Epoch 37/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.2047 - mae: 2.1098
Epoch 38/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.4550 - mae: 2.1502
Epoch 39/50
2350/2350 [==============================] - 3s 1ms/step - loss: 8.7917 - mae: 2.1905
Epoch 40/50
2350/2350 [==============================] - 3s 1ms/step - loss: 9.2576 - mae: 2.1927
Epoch 41/50
2350/2350 [==============================] - 4s 2ms/step - loss: 7.6509 - mae: 2.0499
Epoch 42/50
2350/2350 [==============================] - 3s 1ms/step - loss: 8.1242 - mae: 2.0560
Epoch 43/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.3364 - mae: 2.1247
Epoch 44/50
2350/2350 [==============================] - 4s 2ms/step - loss: 7.6447 - mae: 2.0521
Epoch 45/50
2350/2350 [==============================] - 4s 1ms/step - loss: 8.0203 - mae: 2.0883
Epoch 46/50
2350/2350 [==============================] - 3s 1ms/step - loss: 8.3016 - mae: 2.0913
Epoch 47/50
2350/2350 [==============================] - 4s 2ms/step - loss: 8.1180 - mae: 2.0839
Epoch 48/50
2350/2350 [==============================] - 3s 1ms/step - loss: 7.6610 - mae: 2.0411
Epoch 49/50
2350/2350 [==============================] - 3s 1ms/step - loss: 8.2196 - mae: 2.0711A: 2s  - ETA: 0s - loss: 8.369
Epoch 50/50
2350/2350 [==============================] - 4s 1ms/step - loss: 7.7410 - mae: 2.0464

In [35]:
# Evaluating your model:
res_mse, res_mae = my_model.evaluate(features_test_scaled, labels_test)
print(res_mse, res_mae)

19/19 [==============================] - 0s 1ms/step - loss: 9.8913 - mae: 2.3178
9.891263961791992 2.317817211151123